server:
  port: 8082
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/boot_shiro_jwt?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
mybatis-plus:
  mapper-locations: classpath:/mapper/*/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      db-type: mysql
  configuration:
    cache-enabled: false
